version: '3.7'

services:
    server:
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        expose:
            - "9000"
            - "9003"
        ports:
            - "80:80"
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
            - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
            - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            - database
        networks:
            - inner_net
    database:
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 5
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'superSecr3t'
            MYSQL_USER: 'app_user'
            MYSQL_PASSWORD: 't3rceS'
            MYSQL_DATABASE: 'database'
        networks:
            - inner_net
    myadmin:
        image: phpmyadmin/phpmyadmin:5
        environment:
            PMA_HOST: database
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - inner_net
        volumes:
            - db_admin_data:/var/www/html
    mailcatcher:
        networks:
            - inner_net
        image: yappabe/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
volumes:
    db_data:
    db_admin_data:
networks:
    inner_net:
